import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import '../providers/app_provider.dart';

/// ─────────────────────────────────────────────────────────────────────────
/// i18n sederhana (tanpa paket eksternal, biar tidak belibet).
/// Tambah bahasa/teks cukup di map `_t` di bawah. Pakai: `context.tr('key')`.
/// Bahasa aktif diambil dari AppProvider.language ('id' | 'en').
///
/// `tr` memakai `read` (tidak reaktif sendiri). Layar yang ingin ikut berubah
/// saat bahasa diganti cukup memanggil `context.watch<AppProvider>()` di awal
/// `build` (mayoritas layar sudah). Dengan begitu `context.tr` aman dipakai di
/// mana saja — termasuk di dalam dialog & callback — tanpa error "watch di luar
/// build".
/// ─────────────────────────────────────────────────────────────────────────
class AppStrings {
  AppStrings._();

  static const String fallback = 'id';

  static const Map<String, Map<String, String>> _t = {
    // ── Bahasa Indonesia ──
    'id': {
      // umum
      'save': 'Simpan',
      'cancel': 'Batal',
      'send': 'Kirim',
      'yes': 'Ya',
      'no': 'Tidak',
      'close': 'Tutup',
      'see_all': 'Lihat Semua',
      'open': 'Buka',
      'submit': 'Ajukan',
      'total': 'Total',
      'understood': 'Mengerti',
      // greeting
      'greet_morning': 'Selamat Pagi',
      'greet_afternoon': 'Selamat Siang',
      'greet_evening': 'Selamat Sore',
      'greet_night': 'Selamat Malam',
      'buddy': 'Rekan',
      // bottom nav
      'nav_home': 'Beranda',
      'nav_history': 'Riwayat',
      'nav_leave': 'Cuti',
      'nav_profile': 'Profil',
      // home sections
      'sec_stats': 'Statistik Bulan Ini',
      // recap bulanan
      'recap_title': 'Recap Bulanan',
      'recap_detail': 'Rincian',
      'recap_present': 'Hadir',
      'recap_ontime': 'Tepat Waktu',
      'recap_late': 'Telat',
      'recap_workhours': 'Jam Kerja',
      'recap_hours': 'jam',
      'recap_leave': 'Cuti/Izin',
      'recap_overtime': 'Lembur',
      'recap_packages': 'Paket Terkirim',
      'recap_absent': 'Tidak Hadir',
      'recap_hi': 'Hai,',
      'recap_msg_great': 'Kinerja kamu bulan ini luar biasa! Pertahankan ya.',
      'recap_msg_good': 'Bulan ini bagus! Sedikit lagi menuju sempurna.',
      'recap_msg_improve': 'Yuk tingkatkan kehadiran & ketepatan waktu bulan depan.',
      'sec_location': 'Lokasi Saya',
      'sec_leave_balance': 'Saldo Cuti',
      'sec_quick_menu': 'Menu Cepat',
      'open_map': 'Peta',
      // attendance hero
      'attendance_today': 'Absensi Hari Ini',
      'status_not_yet': 'Belum Absen',
      'status_done': 'Selesai',
      'status_late': 'Terlambat',
      'status_present': 'Hadir',
      'check_in': 'Masuk',
      'check_out': 'Keluar',
      'location': 'Lokasi',
      'in_area': 'Dalam Area',
      'out_area': 'Luar Area',
      'do_check_in': 'Absen Masuk Sekarang',
      'do_check_out': 'Absen Keluar Sekarang',
      // stats
      'stat_present': 'Hadir',
      'stat_late': 'Telat',
      'stat_absent': 'Absen',
      'stat_leave': 'Cuti',
      'on_time': 'Tepat Waktu',
      // leave balance
      'leave_annual': 'Cuti Tahunan',
      'leave_sick': 'Cuti Sakit',
      'leave_personal': 'Cuti Pribadi',
      'remaining': 'sisa',
      'used': 'terpakai',
      'used2': 'Terpakai',
      'sick2': 'Sakit',
      'permit': 'Izin',
      'submitted': 'Diajukan',
      // quick menu
      'menu_chat': 'Chat HR',
      'menu_requests': 'Pengajuan',
      'menu_location': 'Lokasi',
      'menu_sos': 'SOS',
      // banners
      'offline_banner': 'Mode Offline • data akan tersinkron otomatis',
      'data_error_banner': 'Sebagian data gagal dimuat • ketuk untuk detail',
      // sos
      'sos_title': 'Kirim Sinyal SOS?',
      'sos_desc': 'Lokasi dan sinyal darurat Anda akan langsung dipantau oleh admin hub. Gunakan hanya saat darurat.',
      'sos_sent': 'Sinyal SOS terkirim!',
      'out_of_radius': 'Anda berada di luar radius kantor. Mendekatlah ke lokasi kantor.',
      // profile
      'profile_title': 'Profil Saya',
      'sec_account': 'Informasi Akun',
      'sec_services': 'Layanan',
      'sec_card_bio': 'Kartu & Biometrik',
      'sec_security': 'Keamanan',
      'email': 'Email',
      'phone': 'Nomor HP',
      'employee_id': 'ID Karyawan',
      'not_set': 'Belum diatur',
      'request_center': 'Pusat Pengajuan',
      'request_center_sub': 'Pantau cuti, lembur & komplain',
      'chat_hr_sub': 'Hubungi admin secara langsung',
      'help_faq': 'Bantuan & FAQ',
      'help_faq_sub': 'Pertanyaan yang sering diajukan',
      'id_card': 'Kartu Identitas',
      'id_card_sub': 'Kartu pegawai resmi JNE',
      'reenroll_face': 'Daftar Ulang Wajah',
      'reenroll_face_sub': 'Perbarui data pengenalan wajah',
      'change_password': 'Ganti Kata Sandi',
      'change_password_sub': 'Perbarui kata sandi akun Anda',
      'logout': 'Keluar',
      'remaining_annual_leave': 'Sisa Cuti Tahunan',
      'of_days': 'dari',
      'days': 'hari',
      'change_photo': 'Ubah Foto Profil',
      'from_gallery': 'Pilih dari Galeri',
      'take_photo': 'Ambil Foto',
      'photo_updated': 'Foto profil berhasil diperbarui',
      'app_footer': 'JNE Attendance • Martapura Hub',
      'logout_confirm': 'Keluar dari akun?',
      'logout_confirm_desc': 'Anda perlu masuk kembali untuk mengakses absensi dan data Anda.',
      'cp_desc': 'Masukkan kata sandi baru minimal 6 karakter.',
      'new_password_hint': 'Kata sandi baru',
      'cp_min': 'Kata sandi minimal 6 karakter.',
      'password_changed': 'Kata sandi berhasil diubah',
      // settings
      'settings_title': 'Pengaturan',
      'set_display_lang': 'Tampilan & Bahasa',
      'set_dark_mode': 'Mode Gelap',
      'set_dark_mode_sub': 'Tampilan tema gelap untuk mata yang lebih nyaman',
      'set_language': 'Bahasa',
      'set_notif': 'Notifikasi',
      'set_push_notif': 'Notifikasi Push',
      'set_push_notif_sub': 'Terima broadcast & balasan komplain',
      'notif_on': 'Notifikasi aktif',
      'notif_off': 'Notifikasi dimatikan',
      'set_reminder': 'Pengingat Absensi',
      'set_reminder_sub': 'Reminder otomatis sebelum jam masuk',
      'set_office_loc': 'Lokasi Kantor',
      'office_point': 'Titik Kantor',
      'coord_copied': 'Koordinat disalin',
      'office_radius_label': 'Radius Absensi',
      'meters': 'meter',
      'start_time_label': 'Jam Masuk',
      'set_help_support': 'Bantuan & Dukungan',
      'help_center_faq': 'Pusat Bantuan & FAQ',
      'help_center_faq_sub': 'Cek pertanyaan umum dulu sebelum komplain',
      'contact_admin': 'Hubungi Admin',
      'contact_admin_sub': 'Chat langsung dengan admin HUB',
      'set_account_security': 'Akun & Keamanan',
      'change_password2': 'Ganti Password',
      'change_password2_sub': 'Atur ulang kata sandi akun',
      'clear_cache': 'Bersihkan Cache',
      'clear_cache_sub': 'Hapus data sementara untuk troubleshoot',
      'logout_sub': 'Logout dari akun saat ini',
      'set_about': 'Tentang',
      'app_version': 'Versi Aplikasi',
      'update_available': 'Update tersedia',
      'update_now': 'Update',
      'update_force_title': 'Wajib Update',
      'update_force_desc': 'Versi aplikasi ini sudah tidak didukung. Update dulu untuk melanjutkan.',
      'privacy_policy': 'Kebijakan Privasi',
      'privacy_policy_sub': 'Bagaimana kami menangani data Anda',
      'terms_conditions': 'Syarat & Ketentuan',
      'terms_conditions_sub': 'Aturan penggunaan aplikasi',
      'lang_indonesian': 'Bahasa Indonesia',
      'lang_english': 'English',
      'choose_language': 'Pilih Bahasa',
      'effective_date': 'Berlaku efektif: 15 Mei 2026',
      'new_password_hint2': 'Password baru',
      'min_6_chars': 'Minimal 6 karakter',
      'password_changed2': 'Password berhasil diubah',
      'clear_cache_confirm': 'Bersihkan Cache?',
      'clear_cache_confirm_desc': 'Data sementara akan dihapus. Preferensi (mode gelap, bahasa, dll) tetap tersimpan.',
      'clear_btn': 'Bersihkan',
      'cache_cleared': 'Cache dibersihkan',
      // history
      'history_title': 'Riwayat Absensi',
      'leave_permit': 'Izin/Cuti',
      'unsynced_attendance': 'Ada absensi yang belum tersinkron',
      'no_history': 'Belum ada riwayat absensi',
      'status_absent_full': 'Tidak Hadir',
      'status_leave_full': 'Izin / Cuti',
      'report_btn': 'Lapor',
      'dispute_status_prefix': 'Status komplain',
      'tap_open_chat_admin': 'Ketuk untuk buka percakapan dengan admin',
      'confirm_badge': 'KONFIRMASI',
      'ds_resolved': 'Selesai',
      'ds_rejected': 'Ditolak',
      'ds_in_review': 'Sedang Ditinjau',
      'ds_reopened': 'Dibuka Kembali',
      'ds_closed': 'Ditutup',
      'ds_pending': 'Menunggu',
      // leave request
      'leave_request_title': 'Pengajuan Izin',
      'lt_sick': 'Sakit',
      'lt_permission': 'Izin Mendadak',
      'lt_personal': 'Keperluan Pribadi',
      'lt_family': 'Keperluan Keluarga',
      'sec_leave_type': 'Jenis Izin',
      'sec_leave_duration': 'Durasi Izin',
      'sec_leave_reason': 'Alasan & Keterangan',
      'from_date': 'Mulai Tanggal',
      'to_date': 'Sampai Tanggal',
      'pick_date': 'Pilih Tanggal',
      'workdays_counted': 'Hari Kerja Terhitung',
      'reason_hint': 'Tuliskan alasan lengkap Anda di sini...',
      'submit_request_now': 'Kirim Pengajuan Sekarang',
      'pick_leave_date_first': 'Pilih tanggal izin terlebih dahulu',
      'reason_required': 'Alasan izin tidak boleh kosong',
      'leave_submitted': 'Pengajuan izin berhasil dikirim!',
      'send_failed': 'Gagal mengirim',
      // login
      'login_title': 'Masuk',
      'login_subtitle': 'Gunakan akun karyawan JNE Martapura\nuntuk melanjutkan.',
      'email_or_id': 'Email atau ID Karyawan',
      'password_label': 'Kata Sandi',
      'enter_password': 'Masukkan kata sandi',
      'forgot_login': 'Lupa sandi / tidak bisa masuk?',
      'forgot_title': 'Lupa Password?',
      'reset_via_email': 'Reset lewat email',
      'reset_via_email_sub': 'Kirim link reset ke email kamu',
      'report_to_admin': 'Lapor ke admin',
      'report_to_admin_sub': 'Akun belum dibuat / kendala lain',
      'reset_password': 'Reset Password',
      'reset_sent': 'Kalau email terdaftar, link reset sudah dikirim. Cek inbox/spam.',
      'reset_need_email': 'Masukkan email dulu.',
      'reset_invalid_email': 'Format email tidak valid.',
      'reset_failed': 'Gagal mengirim email reset. Coba lagi.',
      'login_footer': 'JNE Martapura · Absensi Karyawan',
      'email_pass_required': 'Email dan kata sandi wajib diisi',
      // attendance (face check-in)
      'camera_not_detected': 'Kamera tidak terdeteksi',
      'error_occurred': 'Terjadi kesalahan',
      'camera_denied': 'Akses kamera ditolak\n\nAktifkan izin kamera di pengaturan ponsel Anda.',
      'camera_start_failed': 'Gagal memulai kamera',
      'waiting_gps': 'Menunggu sinyal GPS...',
      'mock_location_rejected': 'Lokasi palsu terdeteksi • absensi ditolak',
      'out_of_radius_office': 'Di luar radius kantor',
      'face_detect_failed': 'Gagal mendeteksi wajah',
      'times_try_later': 'kali. Coba lagi nanti.',
      'face_not_detected_pre': 'Wajah tidak terdeteksi • sisa',
      'attempts_word': 'percobaan',
      'check_in_label': 'Absen Masuk',
      'check_out_label': 'Absen Keluar',
      'done_check': 'Selesai ✓',
      'late_check': 'Terlambat ⚠',
      'ontime_check': 'Tepat Waktu ✓',
      'outside_office_loc': 'Lokasi Luar Kantor',
      'already_checked_in': 'Anda sudah absen masuk hari ini.',
      'no_checkin_yet': 'Belum ada absen masuk hari ini.',
      'connection_issue': 'Koneksi bermasalah. Periksa internet lalu coba lagi.',
      'save_attendance_failed': 'Gagal menyimpan absensi. Coba lagi sebentar.',
      'face_verification': 'Verifikasi Wajah',
      'tap_for_map': 'Ketuk untuk peta',
      'processing': 'Memproses...',
      'position_face': 'Posisikan wajah di dalam bingkai',
      'saving_attendance': 'Menyimpan absensi...',
      'remote_attendance_active': 'Absensi Luar Kantor Aktif',
      'out_of_area_label': 'Di Luar Area',
      // succeed page
      'enroll_success_title': 'Wajah Terdaftar',
      'attendance_success_title': 'Absensi Berhasil',
      'enroll_success_sub': 'Data wajah Anda sudah aktif.',
      'attendance_success_sub': 'Data absensi berhasil tersimpan.',
      'attendance_type': 'Jenis Absen',
      'time_label': 'Waktu',
      'status_label': 'Status',
      'back_to_home': 'Kembali ke Beranda',
      'view_full_history': 'Lihat Riwayat Lengkap',
      // statistic
      'work_statistics': 'Statistik Kerja',
      'days_present': 'Hari Hadir',
      'leave_sick_label': 'Izin/Sakit',
      'late_minutes': 'Menit Telat',
      'total_hours': 'Total Jam',
      'performance_analysis': 'Analisis Performa',
      'punctuality_label': 'Ketepatan Waktu',
      'location_compliance': 'Kepatuhan Lokasi',
      'hour_effectiveness': 'Efektivitas Jam',
      // my requests
      'overtime_word': 'Lembur',
      'complaint_word': 'Komplain',
      'hours_word': 'jam',
      'empty_leave_req': 'pengajuan cuti',
      'empty_ot_req': 'pengajuan lembur',
      'empty_complaint': 'komplain',
      'no_requests_yet': 'Belum Ada Pengajuan',
      'list_prefix': 'Daftar',
      'list_suffix': 'kamu akan muncul & terpantau statusnya di sini.',
      'cancel_request_q': 'Batalkan Pengajuan?',
      'cancel_request_desc': 'Yakin ingin menarik pengajuan ini? Tindakan tidak bisa dibatalkan.',
      'yes_cancel': 'Ya, Batalkan',
      'request_cancelled': 'Pengajuan berhasil dibatalkan',
      'fail_prefix': 'Gagal',
      'tap_see_admin_reply': 'Ketuk untuk lihat balasan admin',
      'withdraw_request': 'Tarik Pengajuan',
      'st_approved': 'Disetujui',
      'st_rejected': 'Ditolak',
      'st_resolved': 'Selesai',
      'st_pending': 'Menunggu',
      'st_in_review': 'Ditinjau',
      'st_reopened': 'Dibuka Lagi',
      'st_closed': 'Ditutup',
      'st_cancelled': 'Dibatalkan',
      // my location
      'mock_loc_title': 'Lokasi Palsu Terdeteksi',
      'mock_loc_sub': 'Nonaktifkan aplikasi lokasi palsu (fake GPS) untuk bisa absen.',
      'in_office_title': 'Anda di Dalam Area Kantor',
      'in_office_sub': 'Posisi terverifikasi. Anda bisa melakukan absensi.',
      'remote_attendance_sub': 'Anda diizinkan absen dari luar radius kantor.',
      'out_office_title': 'Anda di Luar Area Kantor',
      'out_office_sub': 'Mendekatlah ke kantor hingga masuk radius untuk absen.',
      'distance_to_office': 'Jarak ke Kantor',
      'area_radius': 'Radius Area',
      // overtime
      'overtime_request_title': 'Pengajuan Lembur',
      'fill_overtime_reason': 'Mohon isi alasan lembur',
      'ot_exists_for_date': 'Sudah ada pengajuan lembur untuk tanggal ini.',
      'exceed_limit': 'Melebihi batas',
      'per_month': 'jam/bulan',
      'remaining_word': 'Sisa',
      'overtime_submitted': 'Pengajuan lembur terkirim',
      'ot_date': 'Tanggal Lembur',
      'ot_duration': 'Durasi (Jam)',
      'ot_reason': 'Alasan Lembur',
      'submit_request': 'Kirim Pengajuan',
      'limit_reached': 'Batas Tercapai',
      'ot_reason_hint': 'Contoh: Menyelesaikan pengiriman paket overload di area Martapura Kota.',
      // notifications
      'notifications': 'Notifikasi',
      'unread_word': 'belum dibaca',
      'mark_all_read': 'Tandai semua dibaca',
      'all_marked_read': 'Semua ditandai dibaca',
      'filter_all': 'Semua',
      'filter_unread': 'Belum Dibaca',
      'for_you': 'Untuk Anda',
      'important_badge': 'Penting',
      'act_attendance': 'Absen Sekarang →',
      'act_leave_balance': 'Lihat Saldo Cuti →',
      'act_dispute': 'Buka Komplain →',
      'act_statistic': 'Lihat Statistik →',
      'act_open': 'Buka →',
      'grp_today': 'Hari Ini',
      'grp_yesterday': 'Kemarin',
      'grp_week': 'Minggu Ini',
      'grp_older': 'Lebih Lama',
      'all_read_title': 'Semua sudah dibaca',
      'no_notif_title': 'Tidak ada notifikasi',
      'all_read_sub': 'Inbox Anda bersih. Saatnya fokus kerja!',
      'no_notif_sub': 'Notifikasi penting akan muncul di sini.',
      'mark_as_read': 'Tandai sudah dibaca',
      'just_now': 'baru saja',
      't_min': 'm',
      't_hour': 'j',
      't_day': 'h',
      't_week': 'mg',
      // chat
      'image_too_large': 'Ukuran gambar melebihi batas 5MB.',
      'upload_image_failed': 'Upload gambar gagal. Coba lagi.',
      'admin_hr': 'Admin HR',
      'online_word': 'Online',
      'offline_word': 'Offline',
      'start_conversation': 'Mulai Percakapan',
      'start_conversation_sub': 'Sampaikan pertanyaan, kendala absensi, atau pengajuan langsung ke admin HUB.',
      'admin_typing': 'Admin sedang mengetik',
      'delete_message_q': 'Hapus Pesan?',
      'delete_message_desc': 'Pesan ini akan dihapus untuk semua orang.',
      'delete_word': 'Hapus',
      'photo_selected': 'Foto terpilih',
      'type_message': 'Ketik pesan...',
      // dispute submission
      'report_anomaly': 'Laporkan Anomali',
      'dispute_reason_required': 'Mohon berikan alasan komplain',
      'dispute_title_prefix': 'Komplain absensi',
      'dispute_sent': 'Komplain terkirim. Lanjut ke percakapan dengan admin.',
      'failed_submit': 'Gagal mengirim',
      'complaint_details': 'Detail Komplain',
      'dispute_explain_hint': 'Jelaskan kenapa Anda mengajukan komplain atas catatan absensi ini...',
      'attach_evidence': 'Lampirkan Bukti (Opsional)',
      'tap_capture_photo': 'Ketuk untuk ambil foto',
      'submit_complaint': 'Kirim Komplain',
      // calendar
      'calendar_title': 'Kalender',
      'events_word': 'Acara',
      'invited_word': 'Diundang',
      'no_events': 'Tidak ada acara terjadwal',
      'no_events_sub': 'Pilih tanggal lain atau hubungi Admin',
    },
    // ── English ──
    'en': {
      'save': 'Save',
      'cancel': 'Cancel',
      'send': 'Send',
      'yes': 'Yes',
      'no': 'No',
      'close': 'Close',
      'see_all': 'See All',
      'open': 'Open',
      'submit': 'Request',
      'total': 'Total',
      'understood': 'Got it',
      'greet_morning': 'Good Morning',
      'greet_afternoon': 'Good Afternoon',
      'greet_evening': 'Good Evening',
      'greet_night': 'Good Night',
      'buddy': 'There',
      'nav_home': 'Home',
      'nav_history': 'History',
      'nav_leave': 'Leave',
      'nav_profile': 'Profile',
      'sec_stats': 'This Month\'s Stats',
      // monthly recap
      'recap_title': 'Monthly Recap',
      'recap_detail': 'Details',
      'recap_present': 'Present',
      'recap_ontime': 'On-time',
      'recap_late': 'Late',
      'recap_workhours': 'Work Hours',
      'recap_hours': 'hrs',
      'recap_leave': 'Leave',
      'recap_overtime': 'Overtime',
      'recap_packages': 'Packages',
      'recap_absent': 'Absent',
      'recap_hi': 'Hi,',
      'recap_msg_great': 'Your performance this month is outstanding! Keep it up.',
      'recap_msg_good': 'Good month! Almost perfect.',
      'recap_msg_improve': 'Let\'s improve attendance & punctuality next month.',
      'sec_location': 'My Location',
      'sec_leave_balance': 'Leave Balance',
      'sec_quick_menu': 'Quick Menu',
      'open_map': 'Map',
      'attendance_today': 'Today\'s Attendance',
      'status_not_yet': 'Not Yet',
      'status_done': 'Done',
      'status_late': 'Late',
      'status_present': 'Present',
      'check_in': 'In',
      'check_out': 'Out',
      'location': 'Location',
      'in_area': 'In Area',
      'out_area': 'Out of Area',
      'do_check_in': 'Check In Now',
      'do_check_out': 'Check Out Now',
      'stat_present': 'Present',
      'stat_late': 'Late',
      'stat_absent': 'Absent',
      'stat_leave': 'Leave',
      'on_time': 'On Time',
      'leave_annual': 'Annual Leave',
      'leave_sick': 'Sick Leave',
      'leave_personal': 'Personal Leave',
      'remaining': 'left',
      'used': 'used',
      'used2': 'Used',
      'sick2': 'Sick',
      'permit': 'Permit',
      'submitted': 'Submitted',
      'menu_chat': 'Chat HR',
      'menu_requests': 'Requests',
      'menu_location': 'Location',
      'menu_sos': 'SOS',
      'offline_banner': 'Offline Mode • data will sync automatically',
      'data_error_banner': 'Some data failed to load • tap for details',
      'sos_title': 'Send SOS Signal?',
      'sos_desc': 'Your location and emergency signal will be monitored by the hub admin immediately. Use only in emergencies.',
      'sos_sent': 'SOS signal sent!',
      'out_of_radius': 'You are outside the office radius. Please move closer to the office.',
      'profile_title': 'My Profile',
      'sec_account': 'Account Info',
      'sec_services': 'Services',
      'sec_card_bio': 'Card & Biometric',
      'sec_security': 'Security',
      'email': 'Email',
      'phone': 'Phone Number',
      'employee_id': 'Employee ID',
      'not_set': 'Not set',
      'request_center': 'Request Center',
      'request_center_sub': 'Track leave, overtime & disputes',
      'chat_hr_sub': 'Contact admin directly',
      'help_faq': 'Help & FAQ',
      'help_faq_sub': 'Frequently asked questions',
      'id_card': 'ID Card',
      'id_card_sub': 'Official JNE employee card',
      'reenroll_face': 'Re-enroll Face',
      'reenroll_face_sub': 'Update your face recognition data',
      'change_password': 'Change Password',
      'change_password_sub': 'Update your account password',
      'logout': 'Logout',
      'remaining_annual_leave': 'Remaining Annual Leave',
      'of_days': 'of',
      'days': 'days',
      'change_photo': 'Change Profile Photo',
      'from_gallery': 'Choose from Gallery',
      'take_photo': 'Take Photo',
      'photo_updated': 'Profile photo updated',
      'app_footer': 'JNE Attendance • Martapura Hub',
      'logout_confirm': 'Sign out?',
      'logout_confirm_desc': 'You need to sign in again to access your attendance and data.',
      'cp_desc': 'Enter a new password with at least 6 characters.',
      'new_password_hint': 'New password',
      'cp_min': 'Password must be at least 6 characters.',
      'password_changed': 'Password changed successfully',
      'settings_title': 'Settings',
      'set_display_lang': 'Display & Language',
      'set_dark_mode': 'Dark Mode',
      'set_dark_mode_sub': 'Dark theme for more comfortable viewing',
      'set_language': 'Language',
      'set_notif': 'Notifications',
      'set_push_notif': 'Push Notifications',
      'set_push_notif_sub': 'Receive broadcasts & dispute replies',
      'notif_on': 'Notifications enabled',
      'notif_off': 'Notifications disabled',
      'set_reminder': 'Attendance Reminder',
      'set_reminder_sub': 'Automatic reminder before check-in time',
      'set_office_loc': 'Office Location',
      'office_point': 'Office Point',
      'coord_copied': 'Coordinates copied',
      'office_radius_label': 'Attendance Radius',
      'meters': 'meters',
      'start_time_label': 'Check-in Time',
      'set_help_support': 'Help & Support',
      'help_center_faq': 'Help Center & FAQ',
      'help_center_faq_sub': 'Check common questions before filing a complaint',
      'contact_admin': 'Contact Admin',
      'contact_admin_sub': 'Chat directly with HUB admin',
      'set_account_security': 'Account & Security',
      'change_password2': 'Change Password',
      'change_password2_sub': 'Reset your account password',
      'clear_cache': 'Clear Cache',
      'clear_cache_sub': 'Delete temporary data to troubleshoot',
      'logout_sub': 'Sign out of the current account',
      'set_about': 'About',
      'app_version': 'App Version',
      'update_available': 'Update available',
      'update_now': 'Update',
      'update_force_title': 'Update Required',
      'update_force_desc': 'This app version is no longer supported. Please update to continue.',
      'privacy_policy': 'Privacy Policy',
      'privacy_policy_sub': 'How we handle your data',
      'terms_conditions': 'Terms & Conditions',
      'terms_conditions_sub': 'App usage rules',
      'lang_indonesian': 'Bahasa Indonesia',
      'lang_english': 'English',
      'choose_language': 'Choose Language',
      'effective_date': 'Effective: 15 May 2026',
      'new_password_hint2': 'New password',
      'min_6_chars': 'Minimum 6 characters',
      'password_changed2': 'Password changed successfully',
      'clear_cache_confirm': 'Clear Cache?',
      'clear_cache_confirm_desc': 'Temporary data will be deleted. Preferences (dark mode, language, etc.) are kept.',
      'clear_btn': 'Clear',
      'cache_cleared': 'Cache cleared',
      'history_title': 'Attendance History',
      'leave_permit': 'Leave',
      'unsynced_attendance': 'Some attendance is not yet synced',
      'no_history': 'No attendance history yet',
      'status_absent_full': 'Absent',
      'status_leave_full': 'Leave',
      'report_btn': 'Report',
      'dispute_status_prefix': 'Dispute status',
      'tap_open_chat_admin': 'Tap to open the conversation with admin',
      'confirm_badge': 'CONFIRM',
      'ds_resolved': 'Resolved',
      'ds_rejected': 'Rejected',
      'ds_in_review': 'In Review',
      'ds_reopened': 'Reopened',
      'ds_closed': 'Closed',
      'ds_pending': 'Pending',
      'leave_request_title': 'Leave Request',
      'lt_sick': 'Sick',
      'lt_permission': 'Urgent Permit',
      'lt_personal': 'Personal Matter',
      'lt_family': 'Family Matter',
      'sec_leave_type': 'Leave Type',
      'sec_leave_duration': 'Leave Duration',
      'sec_leave_reason': 'Reason & Details',
      'from_date': 'Start Date',
      'to_date': 'End Date',
      'pick_date': 'Pick Date',
      'workdays_counted': 'Working Days Counted',
      'reason_hint': 'Write your complete reason here...',
      'submit_request_now': 'Submit Request Now',
      'pick_leave_date_first': 'Please pick the leave dates first',
      'reason_required': 'Reason cannot be empty',
      'leave_submitted': 'Leave request sent successfully!',
      'send_failed': 'Failed to send',
      'login_title': 'Sign In',
      'login_subtitle': 'Use your JNE Martapura employee account\nto continue.',
      'email_or_id': 'Email or Employee ID',
      'password_label': 'Password',
      'enter_password': 'Enter your password',
      'forgot_login': 'Forgot password / can\'t sign in?',
      'forgot_title': 'Forgot password?',
      'reset_via_email': 'Reset via email',
      'reset_via_email_sub': 'Send a reset link to your email',
      'report_to_admin': 'Report to admin',
      'report_to_admin_sub': 'Account not created / other issues',
      'reset_password': 'Reset Password',
      'reset_sent': 'If the email is registered, a reset link has been sent. Check inbox/spam.',
      'reset_need_email': 'Enter your email first.',
      'reset_invalid_email': 'Invalid email format.',
      'reset_failed': 'Failed to send reset email. Try again.',
      'login_footer': 'JNE Martapura · Employee Attendance',
      'email_pass_required': 'Email and password are required',
      // attendance (face check-in)
      'camera_not_detected': 'Camera not detected',
      'error_occurred': 'An error occurred',
      'camera_denied': 'Camera access denied\n\nEnable camera permission in your phone settings.',
      'camera_start_failed': 'Failed to start camera',
      'waiting_gps': 'Waiting for GPS signal...',
      'mock_location_rejected': 'Mock location detected • attendance rejected',
      'out_of_radius_office': 'Outside office radius',
      'face_detect_failed': 'Failed to detect face',
      'times_try_later': 'times. Try again later.',
      'face_not_detected_pre': 'Face not detected •',
      'attempts_word': 'attempts left',
      'check_in_label': 'Check In',
      'check_out_label': 'Check Out',
      'done_check': 'Completed ✓',
      'late_check': 'Late ⚠',
      'ontime_check': 'On Time ✓',
      'outside_office_loc': 'Remote Location',
      'already_checked_in': 'You already checked in today.',
      'no_checkin_yet': 'No check-in yet today.',
      'connection_issue': 'Connection problem. Check your internet and try again.',
      'save_attendance_failed': 'Failed to save attendance. Please try again shortly.',
      'face_verification': 'Face Verification',
      'tap_for_map': 'Tap for map',
      'processing': 'Processing...',
      'position_face': 'Position your face within the frame',
      'saving_attendance': 'Saving attendance...',
      'remote_attendance_active': 'Remote Attendance Active',
      'out_of_area_label': 'Out of Area',
      // succeed page
      'enroll_success_title': 'Face Registered',
      'attendance_success_title': 'Attendance Successful',
      'enroll_success_sub': 'Your face data is now active.',
      'attendance_success_sub': 'Your attendance has been saved.',
      'attendance_type': 'Attendance Type',
      'time_label': 'Time',
      'status_label': 'Status',
      'back_to_home': 'Back to Home',
      'view_full_history': 'View Full History',
      // statistic
      'work_statistics': 'Work Statistics',
      'days_present': 'Days Present',
      'leave_sick_label': 'Leave/Sick',
      'late_minutes': 'Late Minutes',
      'total_hours': 'Total Hours',
      'performance_analysis': 'Performance Analysis',
      'punctuality_label': 'Punctuality',
      'location_compliance': 'Location Compliance',
      'hour_effectiveness': 'Hour Effectiveness',
      // my requests
      'overtime_word': 'Overtime',
      'complaint_word': 'Complaint',
      'hours_word': 'hrs',
      'empty_leave_req': 'leave requests',
      'empty_ot_req': 'overtime requests',
      'empty_complaint': 'complaints',
      'no_requests_yet': 'No Requests Yet',
      'list_prefix': 'Your',
      'list_suffix': 'list will appear and be tracked here.',
      'cancel_request_q': 'Cancel Request?',
      'cancel_request_desc': 'Are you sure you want to withdraw this request? This cannot be undone.',
      'yes_cancel': 'Yes, Cancel',
      'request_cancelled': 'Request cancelled successfully',
      'fail_prefix': 'Failed',
      'tap_see_admin_reply': 'Tap to see admin reply',
      'withdraw_request': 'Withdraw Request',
      'st_approved': 'Approved',
      'st_rejected': 'Rejected',
      'st_resolved': 'Resolved',
      'st_pending': 'Pending',
      'st_in_review': 'In Review',
      'st_reopened': 'Reopened',
      'st_closed': 'Closed',
      'st_cancelled': 'Cancelled',
      // my location
      'mock_loc_title': 'Mock Location Detected',
      'mock_loc_sub': 'Disable fake GPS apps to be able to check in.',
      'in_office_title': 'You Are Inside the Office Area',
      'in_office_sub': 'Position verified. You can check in.',
      'remote_attendance_sub': 'You are allowed to check in from outside the office radius.',
      'out_office_title': 'You Are Outside the Office Area',
      'out_office_sub': 'Move closer to the office until within radius to check in.',
      'distance_to_office': 'Distance to Office',
      'area_radius': 'Area Radius',
      // overtime
      'overtime_request_title': 'Overtime Request',
      'fill_overtime_reason': 'Please fill in the overtime reason',
      'ot_exists_for_date': 'There is already an overtime request for this date.',
      'exceed_limit': 'Exceeds limit',
      'per_month': 'hrs/month',
      'remaining_word': 'Remaining',
      'overtime_submitted': 'Overtime request sent',
      'ot_date': 'Overtime Date',
      'ot_duration': 'Duration (Hours)',
      'ot_reason': 'Overtime Reason',
      'submit_request': 'Submit Request',
      'limit_reached': 'Limit Reached',
      'ot_reason_hint': 'Example: Completing overflow package delivery in Martapura Kota area.',
      // notifications
      'notifications': 'Notifications',
      'unread_word': 'unread',
      'mark_all_read': 'Mark all as read',
      'all_marked_read': 'All marked as read',
      'filter_all': 'All',
      'filter_unread': 'Unread',
      'for_you': 'For You',
      'important_badge': 'Important',
      'act_attendance': 'Check In Now →',
      'act_leave_balance': 'View Leave Balance →',
      'act_dispute': 'Open Complaint →',
      'act_statistic': 'View Statistics →',
      'act_open': 'Open →',
      'grp_today': 'Today',
      'grp_yesterday': 'Yesterday',
      'grp_week': 'This Week',
      'grp_older': 'Older',
      'all_read_title': 'All caught up',
      'no_notif_title': 'No notifications',
      'all_read_sub': 'Your inbox is clear. Time to focus!',
      'no_notif_sub': 'Important notifications will appear here.',
      'mark_as_read': 'Mark as read',
      'just_now': 'just now',
      't_min': 'm',
      't_hour': 'h',
      't_day': 'd',
      't_week': 'w',
      // chat
      'image_too_large': 'Image size exceeds the 5MB limit.',
      'upload_image_failed': 'Image upload failed. Please try again.',
      'admin_hr': 'HR Admin',
      'online_word': 'Online',
      'offline_word': 'Offline',
      'start_conversation': 'Start a Conversation',
      'start_conversation_sub': 'Send questions, attendance issues, or requests directly to the HUB admin.',
      'admin_typing': 'Admin is typing',
      'delete_message_q': 'Delete Message?',
      'delete_message_desc': 'This message will be deleted for everyone.',
      'delete_word': 'Delete',
      'photo_selected': 'Photo selected',
      'type_message': 'Type a message...',
      // dispute submission
      'report_anomaly': 'Report Anomaly',
      'dispute_reason_required': 'Please provide a reason for the dispute',
      'dispute_title_prefix': 'Attendance complaint',
      'dispute_sent': 'Complaint sent. Continuing to the conversation with admin.',
      'failed_submit': 'Failed to submit',
      'complaint_details': 'Complaint Details',
      'dispute_explain_hint': 'Explain why you are disputing this attendance record...',
      'attach_evidence': 'Attach Evidence (Optional)',
      'tap_capture_photo': 'Tap to capture photo',
      'submit_complaint': 'Submit Complaint',
      // calendar
      'calendar_title': 'Calendar',
      'events_word': 'Events',
      'invited_word': 'Invited',
      'no_events': 'No scheduled events',
      'no_events_sub': 'Pick another date or contact Admin',
    },
  };

  /// Nama bulan terlokalisasi (untuk dropdown/format manual).
  static const Map<String, List<String>> _months = {
    'id': [
      'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
      'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember',
    ],
    'en': [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December',
    ],
  };

  static List<String> months(String lang) => _months[lang] ?? _months[fallback]!;

  /// Inisial hari (Senin-first) terlokalisasi untuk grid kalender.
  static const Map<String, List<String>> _weekdays = {
    'id': ['S', 'S', 'R', 'K', 'J', 'S', 'M'],
    'en': ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  };

  static List<String> weekdays(String lang) => _weekdays[lang] ?? _weekdays[fallback]!;

  static String of(String lang, String key) {
    return _t[lang]?[key] ?? _t[fallback]?[key] ?? key;
  }
}

extension TrX on BuildContext {
  /// Terjemahkan `key` sesuai bahasa aktif (non-reaktif — lihat catatan di atas).
  String tr(String key) => AppStrings.of(read<AppProvider>().language, key);
}
